server:
  port: 8080 # El puerto donde correrá este microservicio

spring:
  # 1. CONFIGURACIÓN DE LA BASE DE DATOS CLOUD
  datasource:
    # Cambia esto por el endpoint de tu base de datos en AWS (RDS o EC2)
    url: jdbc:mysql://TU_ENDPOINT_DE_AWS:3306/pedidos360
    username: TU_USUARIO_DB
    password: TU_PASSWORD_DB
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Crea o actualiza las tablas automáticamente basándose en tu modelo
    show-sql: true # Útil para ver las consultas en la consola mientras desarrollas
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # 2. CONFIGURACIÓN DE SEGURIDAD (JWT / IDaaS)
  security:
    oauth2:
      resourceserver:
        jwt:
          # Reemplaza TU_TENANT_ID con el ID del tenant que crearás en Azure AD
          issuer-uri: 6fb3d735-1c10-4007-b977-7dbea3388386
          # Reemplaza TU_CLIENT_ID con el ID de la aplicación que registrarás
          audiences: 43503a71-e4f5-4f4b-a283-185c42b093f0